### ISSUE TITLE
Core coin

### ISSUE THREAD

**Issue by Moudie1** [core-coin/wallet-generator#15]

**Comment by raisty** [comment]
Please, define your issue topic and we will assist you. Feel free to re-open the issue.

**Comment by Moudie1** [comment]
Hoe to open a wallet

**Comment by raisty** [comment]
Please, follow the readme file: https://github.com/core-coin/wallet-generator#readme

If you have any difficulties, please reopen this issue with the technical description.

**Comment by Moudie1** [comment]
Cant open zip file Wallet genarator

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Rastislav ***@***.***>
Verzonden: Monday, April 4, 2022 1:22:14 AM
Aan: core-coin/wallet-generator ***@***.***>
CC: Moudie1 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [core-coin/wallet-generator] Core coin (Issue #15)


Please, follow the readme file: https://github.com/core-coin/wallet-generator#readme

If you have any difficulties, please reopen this issue with the technical description.

**Comment by Moudie1** [comment]
I create a raw wallet is this good so I need to create a nother wallet ?

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: RLSLOODGIETERS . ***@***.***>
Verzonden: Monday, April 4, 2022 6:13:04 AM
Aan: core-coin/wallet-generator ***@***.***>; core-coin/wallet-generator ***@***.***>
CC: Author ***@***.***>
Onderwerp: Re: [core-coin/wallet-generator] Core coin (Issue #15)

Cant open zip file Wallet genarator

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Rastislav ***@***.***>
Verzonden: Monday, April 4, 2022 1:22:14 AM
Aan: core-coin/wallet-generator ***@***.***>
CC: Moudie1 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [core-coin/wallet-generator] Core coin (Issue #15)


Please, follow the readme file: https://github.com/core-coin/wallet-generator#readme

If you have any difficulties, please reopen this issue with the technical description.

**Comment by raisty** [comment]
This discussion is related to technical difficulties and issues. Please, if you have that kind of problem, open a new issue and describe the case. Thank you.
