### ISSUE TITLE
Error message miner not found

### ISSUE THREAD

**Issue by earld1604** [core-coin/wallet-generator#24]
L.s., I tried to install the Corecoin miner on my Windows 10 host witth Ubuntu guest. I followed the instructions from https://catchthatrabbit.com/start-mining and also from the mining tutorial from the https://blog.coreblockchain.cc/posts/iot/mining.html#step-1-download-a-crypto-wallet. But when I select y to start mining, message “miner not found” is displayed. What is reason that miner is not found? Looking  forward to your tips/suggestions, thank you Earl
![9EDA46AD-30C6-4028-A67C-5D2BDA36F6F4](https://user-images.githubusercontent.com/105171841/167692764-ac5e15f9-86bf-44a9-9d8a-4b22628d1f06.jpeg)

**Comment by earld1604** [comment]
with help from discord member this issue was solved

**Comment by raisty** [comment]
I am glad that the community helps you.
