### ISSUE TITLE
Wallet Validation

### ISSUE THREAD

**Issue by Fry2412** [core-coin/wallet-generator#30]
### Problem

Hey,
not really a bug but a question that's bugging me.
I am mining core coins for a short time and have also apparently successfully created a wallet. Is there currently any way to validate this wallet, for example through test transactions?
I would like to be 100% sure that I have control over the wallet. Actually, no error should have occurred, but control is better than trust.

I have generated a password protected file. Is there a way to get the private key out?

### Solution

No solution in mind besides a friendly reply :)

**Comment by rastislavcore** [comment]
In Core Blockchain is the system available called ICAN, which is putting after the network prefix two digits to verify the validity of the wallet (e.g. CB99…) From that checksum, you can check the validity of the address. Ok, then if the wallet is valid, probably you want to know if you can move the funds.
Short answer - if you have the valid private key for that wallet or any way to reconstruct it (mnemonic, etc.) you can move them.

You can get your private key out from the UTC file if you remember your password. The best will be to use `xcbkey` tool, which can be obtained from go-core distribution by compiling it. (please, compile it yourself to avoid being scammed)

But if you want to be 100% sure you can move funds, please do the transaction with a small amount of the funds.

Some ICAN tools:
https://github.com/cryptohub-digital/ican-validate.sh (this is probably the easiest to run)
https://github.com/cryptohub-digital/ican.js
https://github.com/cryptohub-digital/go-ican
https://github.com/cryptohub-digital/IcanNet
https://github.com/cryptohub-digital/ican.gs
